from jiradata import get_by_path, get_top_label, get_jiradata,get_comments
from jiradata import jiradata

dummy_issue = {'expand': 'operations,versionedRepresentations,editmeta,changelog,renderedFields',
               'id': '1035906',
               'self': 'https://jira.fr.anotherworld/rest/api/2/issue/1035906',
               'key': 'DELTA-1931',
               'fields': {'customfield_13100': None,
                          'customfield_13101': None,
                          'fixVersions': [],
                          'resolution': None,
                          'customfield_13501': None,
                          'customfield_12800': None,
                          'customfield_12801': None,
                          'customfield_12804': None,
                          'customfield_12803': None,
                          'lastViewed': None,
                          'customfield_15110': None,
                          'customfield_15111': None,
                          'customfield_14300': None,
                          'customfield_15114': None,
                          'customfield_15115': None,
                          'customfield_15112': None,
                          'customfield_15113': None,
                          'customfield_14700': None,
                          'priority': {'self': 'https://jira.fr.anotherworld/rest/api/2/priority/1',
                                       'iconUrl': 'https://jira.fr.anotherworld/images/icons/priorities/highest.svg',
                                       'name': 'Highest',
                                       'id': '1'},
                          'customfield_15116': None,
                          'customfield_10103': None,
                          'labels': ['TeamA', 'DSS', 'Support'],
                          'customfield_13602': None,
                          'customfield_15109': None,
                          'customfield_11701': None,
                          'aggregatetimeoriginalestimate': None,
                          'timeestimate': None,
                          'versions': [],
                          'issuelinks': [],
                          'assignee': {'self': 'https://jira.fr.anotherworld/rest/api/2/user?username=uzumaki.kickass%40freeworld.com',
                                       'name': 'uzumaki.kickass@freeworld.com',
                                       'key': 'uzumaki.kickass@freeworld.com',
                                       'emailAddress': 'uzumaki.kickass@freeworld.com',
                                       'avatarUrls': {'48x48': 'https://jira.fr.anotherworld/secure/useravatar?avatarId=10122',
                                                      '24x24': 'https://jira.fr.anotherworld/secure/useravatar?size=small&avatarId=10122',
                                                      '16x16': 'https://jira.fr.anotherworld/secure/useravatar?size=xsmall&avatarId=10122',
                                                      '32x32': 'https://jira.fr.anotherworld/secure/useravatar?size=medium&avatarId=10122'},
                                       'displayName': 'uzumaki ROJO BRAVO',
                                       'active': True,
                                       'timeZone': 'Europe/Paris'},
                          'status': {'self': 'https://jira.fr.anotherworld/rest/api/2/status/3',
                                     'description': 'This issue is being actively worked on at the moment by the assignee.',
                                     'iconUrl': 'https://jira.fr.anotherworld/images/icons/statuses/inprogress.png',
                                     'name': 'In Progress',
                                     'id': '3',
                                     'statusCategory': {'self': 'https://jira.fr.anotherworld/rest/api/2/statuscategory/4',
                                                        'id': 4,
                                                        'key': 'indeterminate',
                                                        'colorName': 'yellow',
                                                        'name': 'In Progress'}},
                          'components': [{'self': 'https://jira.fr.anotherworld/rest/api/2/component/45698',
                                          'id': '45698',
                                          'name': 'MyDomain',
                                          'description': 'Composant MyDomain'}],
                          'customfield_15100': None,
                          'customfield_15103': None,
                          'customfield_15101': None,
                          'customfield_13200': None,
                          'customfield_15102': None,
                          'customfield_11024': None,
                          'customfield_15107': None,
                          'customfield_15108': None,
                          'customfield_13601': None,
                          'customfield_11301': None,
                          'customfield_15105': None,
                          'customfield_13600': None,
                          'customfield_15106': None,
                          'customfield_11017': None,
                          'customfield_11018': None,
                          'customfield_10723': None,
                          'aggregatetimeestimate': None,
                          'customfield_10728': None,
                          'creator': {'self': 'https://jira.fr.anotherworld/rest/api/2/user?username=uzumaki.kickass%40freeworld.com',
                                      'name': 'uzumaki.kickass@freeworld.com',
                                      'key': 'uzumaki.kickass@freeworld.com',
                                      'emailAddress': 'uzumaki.kickass@freeworld.com',
                                      'avatarUrls': {'48x48': 'https://jira.fr.anotherworld/secure/useravatar?avatarId=10122',
                                                     '24x24': 'https://jira.fr.anotherworld/secure/useravatar?size=small&avatarId=10122',
                                                     '16x16': 'https://jira.fr.anotherworld/secure/useravatar?size=xsmall&avatarId=10122',
                                                     '32x32': 'https://jira.fr.anotherworld/secure/useravatar?size=medium&avatarId=10122'},
                                      'displayName': 'uzumaki ROJO BRAVO',
                                      'active': True,
                                      'timeZone': 'Europe/Paris'},
                          'customfield_14000': None,
                          'subtasks': [],
                          'customfield_14400': None,
                          'reporter': {'self': 'https://jira.fr.anotherworld/rest/api/2/user?username=uzumaki.kickass%40freeworld.com',
                                       'name': 'uzumaki.kickass@freeworld.com',
                                       'key': 'uzumaki.kickass@freeworld.com',
                                       'emailAddress': 'uzumaki.kickass@freeworld.com',
                                       'avatarUrls': {'48x48': 'https://jira.fr.anotherworld/secure/useravatar?avatarId=10122',
                                                      '24x24': 'https://jira.fr.anotherworld/secure/useravatar?size=small&avatarId=10122',
                                                      '16x16': 'https://jira.fr.anotherworld/secure/useravatar?size=xsmall&avatarId=10122',
                                                      '32x32': 'https://jira.fr.anotherworld/secure/useravatar?size=medium&avatarId=10122'},
                                       'displayName': 'Uzumaki KickAss',
                                       'active': True,
                                       'timeZone': 'Europe/Paris'},
                          'customfield_11011': None,
                          'customfield_12101': [{'name': 'Product Owner approved',
                                                 'checked': False,
                                                 'mandatory': True,
                                                 'option': True,
                                                 'id': 12212,
                                                 'rank': 0},
                                                {'name': 'Support approved',
                                                 'checked': False,
                                                 'mandatory': False,
                                                 'option': True,
                                                 'id': 14207,
                                                 'rank': 1}],
                          'customfield_14001': None,
                          'customfield_14002': None,
                          'aggregateprogress': {'progress': 0, 'total': 0},
                          'customfield_13306': None,
                          'customfield_13305': None,
                          'customfield_13701': None,
                          'customfield_11800': None,
                          'customfield_11803': None,
                          'progress': {'progress': 0, 'total': 0},
                          'votes': {'self': 'https://jira.fr.anotherworld/rest/api/2/issue/DELTA-1931/votes',
                                    'votes': 0,
                                    'hasVoted': False},
                          'issuetype': {'self': 'https://jira.fr.anotherworld/rest/api/2/issuetype/10100',
                                        'id': '10100',
                                        'description': 'A task that needs to be done.',
                                        'iconUrl': 'https://jira.fr.anotherworld/secure/viewavatar?size=xsmall&avatarId=10318&avatarType=issuetype',
                                        'name': 'Task',
                                        'subtask': False,
                                        'avatarId': 10318},
                          'timespent': None,
                          'project': {'self': 'https://jira.fr.anotherworld/rest/api/2/project/13601',
                                      'id': '13601',
                                      'key': 'DELTA',
                                      'name': 'Ninja Corporate',
                                      'projectTypeKey': 'software',
                                      'avatarUrls': {'48x48': 'https://jira.fr.anotherworld/secure/projectavatar?avatarId=10324',
                                                     '24x24': 'https://jira.fr.anotherworld/secure/projectavatar?size=small&avatarId=10324',
                                                     '16x16': 'https://jira.fr.anotherworld/secure/projectavatar?size=xsmall&avatarId=10324',
                                                     '32x32': 'https://jira.fr.anotherworld/secure/projectavatar?size=medium&avatarId=10324'},
                                      'projectCategory': {'self': 'https://jira.fr.anotherworld/rest/api/2/projectCategory/11001',
                                                          'id': '11001',
                                                          'description': '',
                                                          'name': 'TRIO'}},
                          'customfield_13300': None,
                          'aggregatetimespent': None,
                          'customfield_11004': None,
                          'customfield_13304': None,
                          'customfield_13700': None,
                          'customfield_13303': None,
                          'customfield_11005': None,
                          'customfield_14902': None,
                          'customfield_14900': None,
                          'customfield_14901': None,
                          'customfield_10704': None,
                          'resolutiondate': None,
                          'customfield_10706': None,
                          'workratio': -1,
                          'watches': {'self': 'https://jira.fr.anotherworld/rest/api/2/issue/DELTA-1931/watchers',
                                      'watchCount': 1,
                                      'isWatching': False},
                          'created': '2020-03-23T17:38:38.000+0100',
                          'customfield_14500': None,
                          'customfield_12600': None,
                          'customfield_14501': None,
                          'customfield_13801': None,
                          'customfield_13800': None,
                          'customfield_10810': None,
                          'customfield_10816': None,
                          'customfield_10817': None,
                          'customfield_10818': None,
                          'updated': '2020-03-23T17:52:21.000+0100',
                          'timeoriginalestimate': None,
                          'customfield_13000': None,
                          'description': 'Let me write something\r\nReally long\r\n\r\nCause why not ?',
                          'customfield_11100': None,
                          'customfield_11101': None,
                          'customfield_11102': None,
                          'customfield_11500': None,
                          'customfield_10005': '0|i43prz:',
                          'customfield_10006': None,
                          'customfield_11616': None,
                          'customfield_10802': None,
                          'customfield_10803': [],
                          'customfield_10804': None,
                          'customfield_10805': None,
                          'customfield_10806': None,
                          'summary': 'How to escape ?',
                          'customfield_10000': 'DELTA-1298',
                          'customfield_14200': None,
                          'customfield_14601': None,
                          'customfield_11610': None,
                          'customfield_10004': None,
                          'customfield_14600': None,
                          'customfield_13900': '{summaryBean=com.atlassian.jira.plugin.devstatus.rest.SummaryBean@6db33133[summary={pullrequest=com.atlassian.jira.plugin.devstatus.rest.SummaryItemBean@17a559fd[overall=PullRequestOverallBean{stateCount=0, state=\'OPEN\', details=PullRequestOverallDetails{openCount=0, mergedCount=0, declinedCount=0}},byInstanceType={}], build=com.atlassian.jira.plugin.devstatus.rest.SummaryItemBean@6b85b8ed[overall=com.atlassian.jira.plugin.devstatus.summary.beans.BuildOverallBean@56527ed1[failedBuildCount=0,successfulBuildCount=0,unknownBuildCount=0,count=0,lastUpdated=<null>,lastUpdatedTimestamp=<null>],byInstanceType={}], review=com.atlassian.jira.plugin.devstatus.rest.SummaryItemBean@da14e49[overall=com.atlassian.jira.plugin.devstatus.summary.beans.ReviewsOverallBean@4be898bb[stateCount=0,state=<null>,dueDate=<null>,overDue=false,count=0,lastUpdated=<null>,lastUpdatedTimestamp=<null>],byInstanceType={}], deployment-environment=com.atlassian.jira.plugin.devstatus.rest.SummaryItemBean@d6c03fb[overall=com.atlassian.jira.plugin.devstatus.summary.beans.DeploymentOverallBean@480d4071[topEnvironments=[],showProjects=false,successfulCount=0,count=0,lastUpdated=<null>,lastUpdatedTimestamp=<null>],byInstanceType={}], repository=com.atlassian.jira.plugin.devstatus.rest.SummaryItemBean@4fd99c3f[overall=com.atlassian.jira.plugin.devstatus.summary.beans.CommitOverallBean@40fbf83f[count=0,lastUpdated=<null>,lastUpdatedTimestamp=<null>],byInstanceType={}], branch=com.atlassian.jira.plugin.devstatus.rest.SummaryItemBean@2d655800[overall=com.atlassian.jira.plugin.devstatus.summary.beans.BranchOverallBean@f498b15[count=0,lastUpdated=<null>,lastUpdatedTimestamp=<null>],byInstanceType={}]},errors=[],configErrors=[]], devSummaryJson={"cachedValue":{"errors":[],"configErrors":[],"summary":{"pullrequest":{"overall":{"count":0,"lastUpdated":null,"stateCount":0,"state":"OPEN","details":{"openCount":0,"mergedCount":0,"declinedCount":0,"total":0},"open":true},"byInstanceType":{}},"build":{"overall":{"count":0,"lastUpdated":null,"failedBuildCount":0,"successfulBuildCount":0,"unknownBuildCount":0},"byInstanceType":{}},"review":{"overall":{"count":0,"lastUpdated":null,"stateCount":0,"state":null,"dueDate":null,"overDue":false,"completed":false},"byInstanceType":{}},"deployment-environment":{"overall":{"count":0,"lastUpdated":null,"topEnvironments":[],"showProjects":false,"successfulCount":0},"byInstanceType":{}},"repository":{"overall":{"count":0,"lastUpdated":null},"byInstanceType":{}},"branch":{"overall":{"count":0,"lastUpdated":null},"byInstanceType":{}}}},"isStale":false}}',
                          'customfield_11600': None,
                          'customfield_11205': None,
                          'customfield_11603': None,
                          'environment': None,
                          'customfield_11208': None,
                          'duedate': None}}

dummy_comment = {'self': 'https://jira.io/rest/api/2/issue/782674/comment/747211',
                 'id': '747211',
                 'author': {'self': 'https://jira.io/rest/api/2/user?username=takzeo.musashi%40legends.com',
                            'name': 'takzeo.musashi@legends.com',
                            'key': 'takzeo.musashi@legends.com',
                            'emailAddress': 'takzeo.musashi@legends.com',
                            'avatarUrls': {'48x48': 'https://jira.io/secure/useravatar?ownerId=takzeo.musashi%40legends.com&avatarId=20630',
                                           '24x24': 'https://jira.io/secure/useravatar?size=small&ownerId=takzeo.musashi%40legends.com&avatarId=20630',
                                           '16x16': 'https://jira.io/secure/useravatar?size=xsmall&ownerId=takzeo.musashi%40legends.com&avatarId=20630',
                                           '32x32': 'https://jira.io/secure/useravatar?size=medium&ownerId=takzeo.musashi%40legends.com&avatarId=20630'},
                            'displayName': 'Takzeo Musashi',
                            'active': True,
                            'timeZone': 'Europe/Paris'},
                 'body': 'No pain, no gain',
                 'updateAuthor': {'self': 'https://jira.io/rest/api/2/user?username=takzeo.musashi%40legends.com',
                                  'name': 'takzeo.musashi@legends.com',
                                  'key': 'takzeo.musashi@legends.com',
                                  'emailAddress': 'takzeo.musashi@legends.com',
                                  'avatarUrls': {'48x48': 'https://jira.io/secure/useravatar?ownerId=takzeo.musashi%40legends.com&avatarId=20630',
                                                 '24x24': 'https://jira.io/secure/useravatar?size=small&ownerId=takzeo.musashi%40legends.com&avatarId=20630',
                                                 '16x16': 'https://jira.io/secure/useravatar?size=xsmall&ownerId=takzeo.musashi%40legends.com&avatarId=20630',
                                                 '32x32': 'https://jira.io/secure/useravatar?size=medium&ownerId=takzeo.musashi%40legends.com&avatarId=20630'},
                                  'displayName': 'Takzeo Musashi',
                                  'active': True,
                                  'timeZone': 'Europe/Paris'},
                 'created': '2020-03-18T14:41:00.289+0100',
                 'updated': '2020-03-18T14:41:00.289+0100'}


def test_get_by_path():
    dummy = {'a': 1,
             'b': {'c': 'ok', 'd': 3}}
    assert get_by_path(dummy, ('a')) == 1
    assert get_by_path(dummy, ('b', 'c')) == 'ok'


def test_get_top_label():
    dummy_labels = [{'fields': {'labels': ['pirate', 'marine']}},
                    {'fields': {'labels': ['hero', 'vilain']}},
                    {'fields': {'labels': ['pirate']}},
                    {'fields': {'labels': ['marine']}}]

    assert get_top_label(dummy_labels) == {
        ('pirate', 2/4), ('marine', 2/4), ('hero', 1/4), ('vilain', 1/4)}


def test_get_issue_owner():
    jiradata.get_issue_owner(dummy_issue) == 'Uzumaki Kickass'


def test_get_jiradata():
    result = get_jiradata(dummy_issue)
    assert len(result.keys()) == 10


def test_struct_comment():
    parts = jiradata.struct_comment(dummy_comment, 100)
    assert parts == ('Takzeo Musashi', 'No pain, no gain')
    parts = jiradata.struct_comment(dummy_comment, 5)
    assert parts == ('Takzeo Musashi', 'too long')


def test_get_comments():
    comments = {'key': 'myid','fields': {'comment': {'comments': [dummy_comment]}}}
    parts = get_comments(comments)
    assert parts['ref'] == 'myid'

